# Disable the blank line at the start of the prompt
add_newline = false

# add a longer command timeout than default (500)
command_timeout = 750

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](green)" # The "success_symbol" segment is being set to "➜" with the color "green"
error_symbol = "[➜](red)" # The "error_symbol" segment is being set to "➜" with the color "red"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
