#!/usr/bin/env bash
# Install all dotfiles into the home directory

DOTFILESDIRREL="$(dirname "$0")"
cd "$DOTFILESDIRREL"/.. || exit
DOTFILESDIR=$(pwd -P)

[ "$(uname -s)" = "Darwin" ] && export OSX=1 && export UNIX=1
[ "$(uname -s)" = "Linux" ] && export LINUX=1 && export UNIX=1

for DOTFILE in *; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d "$DOTFILE" ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  # shellcheck disable=SC2196
  echo "$DOTFILE" | egrep -q '(^script/$|\.txt$|\.md$)' && continue

  # shellcheck disable=SC2001
  echo "$DOTFILE" | grep -q '\.sh' \
    && HOMEFILE="$HOME/.$(echo "$DOTFILE" | sed -e 's/\.sh//')"

  if [ $UNIX ]
  then
    if [ -L "$HOMEFILE" ] && ! [ -d "$DOTFILE" ]
    then
      ln -sfv "$DIRFILE" "$HOMEFILE"
    else
      rm -rv "$HOMEFILE"
      ln -sv "$DIRFILE" "$HOMEFILE"
    fi
  else
    cp -rv "$DIRFILE" "$HOMEFILE"
  fi
done
